# speaker related metrics
# -- spk_similarity: speaker cosine similarity
#                    model tag can be any ESPnet-SPK huggingface repo at
#                    https://huggingface.co/espnet
- name: speaker
  model_tag: default

